[package]
name    = "observer_async"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
futures = "0.3.28"
futures-util = "0.3.28"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }

